docker:
  image_name: rest-bot
  registry_prefix: us.gcr.io
  folder_path: rest-bot

gcloud:
  bucket_id: rest-bot
  bucket_prefix: gs://
  bucket_path: ames-xgboost

k8s:
  namespace: hpi-ml-applications

artifact_store:
  host: "metadata-grpc-service.kubeflow"
  port: 8080
  workspace:
    name: "ames-workspace"
    description: "workspace for xgboost demo on the ames dataset"
  run:
    description: "a run from local"
  execution:
    description: "execution for example training"
